---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: rayen91130
    password: 181jmt0628////

- name: Push the Docker image into the repo
  shell: docker push rayen91130/devops:latest
